---
- name: Advanced Demo Playbook
  hosts: all
  become: yes
  vars:
    packages:
      - git
      - curl
    app_user: devuser
    web_root: /opt/webapp

  pre_tasks:
    - name: Show OS info
      ansible.builtin.debug:
        var: ansible_distribution

  tasks:

    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      tags: install

    - name: Create application user
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /bin/bash
        comment: "Web Application User"
      when: ansible_distribution == "Ubuntu"

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Create multiple sub-directories
      ansible.builtin.file:
        path: "{{ web_root }}/{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
      loop:
        - logs
        - tmp
        - uploads

    - name: Deploy config file using template
      ansible.builtin.template:
        src: templates/config.j2
        dest: "{{ web_root }}/config.ini"
      notify: restart service

    - name: Start dummy service (example)
      ansible.builtin.service:
        name: cron
        state: started
      register: cron_status

    - name: Check cron service result
      ansible.builtin.debug:
        var: cron_status
      when: cron_status.changed

    - name: Run risky block
      block:
        - name: Try creating a file
          ansible.builtin.command: touch /root/protected_file.txt

      rescue:
        - name: Notify failure
          ansible.builtin.debug:
            msg: "Creation failed, likely due to permissions."

      always:
        - name: Always runs
          ansible.builtin.debug:
            msg: "This runs whether block fails or not."

    - name: Print custom message
      ansible.builtin.debug:
        msg: "This playbook finished running on {{ inventory_hostname }}."

  handlers:
    - name: restart service
      ansible.builtin.debug:
        msg: "Restarting dummy service as config changed."

