---
- name: Install and configure MySQL
  hosts: all
  become: yes
  vars:
    mysql_root_password: root123

  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: true

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: true

    - name: Secure MySQL root user
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host_all: true
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Create studentdb database
      mysql_db:
        name: studentdb
        state: present
