---
- name: Install Web Server
  hosts: all
  become: yes
  vars:
    package_name: apache2
  tasks:
    - name: Install the package
      apt:
        name: "{{ package_name }}"
        state: present


    - name: Start and enable the web server
      service:
        name: "{{ package_name }}"
        state: started
        enabled: yes