---
- name: Configure Apache
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
   

    - name: Copy Apache Config
      copy:
        src: apache.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted